### PR TITLE
add input checker for given OS and ARCH values

### PR DESCRIPTION
**Pull request by vigo**
- checks options against `go tool dist list`
- adds go binary via `command -v go`

### CODE REVIEW

**Comment by MartinHeinz** [comment]
Hi, I like the change, but unfortunately it doesn't work for me - running `make` returns:

```bash
./build/build.sh: line 36: syntax error: bad substitution
make: *** [Makefile:83: .go/bin/linux_amd64/app.stamp] Error 2
```

**Comment by vigo** [comment]
aaaaaaaaah... i missed that first line... ok, i'll fix for "sh"...

**Comment by vigo** [comment]
well, is docker running while calling "make" ?

**Comment by MartinHeinz** [comment]
Generally, `build.sh` is meant to be run inside docker container (as part of the `make` target). I assume you used `build.sh` independently?

Now I'm not sure how beneficial this change is considering that it doesn't improve the intended usage via `make` and `docker`, but... I would merge it if it doesn't break `make` target.

**Comment by vigo** [comment]
ok no problem.

**Pull request closed without merging**
